[package]
name = "Rust_C_Sample"
version = "0.1.0"
authors = ["Binit Kumar <bkumar@rocketsoftware.com>"]
edition = "2018"
build = "build.rs"
links = "db2app64"

[lib]
name = "CCODE"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
cc = "1.0"
[dependencies]
winapi = "0.2"
user32-sys = "0.2"
